// Panel editorial y administrativo.
(function(){
  const api=window.JeanPipiApi,ui=window.JeanPipiUI;
  let currentUser=null,currentArticleId=null,articlePage=1,viewsChart=null,categories=[],authors=[];
  const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  function cell(text){const td=document.createElement('td');td.textContent=text==null?'':String(text);return td;}
  function action(label,handler){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',handler);return b;}
  function badge(value){const span=document.createElement('span');span.className='status-badge status-'+value;span.textContent=value;return span;}
  function openPanel(name){qsa('.admin-nav').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));qsa('.admin-panel').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===name));qs('#adminSidebar').classList.remove('open');if(name==='dashboard')loadDashboard();if(name==='articles')loadArticles(1);if(name==='categories')loadCategories();if(name==='users')loadUsers();if(name==='comments')loadComments();if(name==='media')loadMedia();if(name==='home')loadHomeSections();if(name==='audit')loadDashboard();}
  async function initialize(){
    try{const session=await api.get('/api/v1/auth/session');currentUser=session.user;if(!currentUser||currentUser.rol==='LECTOR'){location.href=api.context+'/login.jsp?next=admin.jsp';return;}api.setCsrf(session.csrfToken);qs('#adminUserName').textContent=currentUser.nombre+' | '+currentUser.rol;applyRole();await Promise.all([loadOptions(),loadDashboard()]);}
    catch(e){location.href=api.context+'/login.jsp?next=admin.jsp';}
  }
  function applyRole(){
    qsa('.role-admin').forEach(el=>el.classList.toggle('d-none',currentUser.rol!=='ADMIN'));
    qsa('.role-editor').forEach(el=>el.classList.toggle('d-none',!['ADMIN','EDITOR'].includes(currentUser.rol)));
    qsa('.publish-option').forEach(el=>el.disabled===undefined?null:el.disabled=currentUser.rol==='AUTOR');
    qs('#articleAuthor').disabled=currentUser.rol==='AUTOR';qs('#articleFeatured').disabled=currentUser.rol==='AUTOR';
  }
  async function loadOptions(){
    const results=await Promise.allSettled([api.get('/api/v1/categories'),api.get('/api/v1/users/authors')]);categories=results[0].status==='fulfilled'?results[0].value:[];authors=results[1].status==='fulfilled'?results[1].value:[];
    const cat=qs('#articleCategory');cat.innerHTML='<option value="">Sin categoria</option>';categories.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.nombre;cat.appendChild(o);});
    const aut=qs('#articleAuthor');aut.innerHTML='';authors.forEach(u=>{const o=document.createElement('option');o.value=u.id;o.textContent=u.nombre+' ('+u.rol+')';aut.appendChild(o);});if(currentUser.rol==='AUTOR')aut.value=String(currentUser.id);
  }
  async function loadDashboard(){
    try{const data=await api.get('/api/v1/dashboard');renderMetrics(data);renderTop(data.topArticles||[]);renderChart(data.viewsDaily||[]);renderAudit(data.auditoria||[]);renderSections(data.secciones||[]);}catch(e){}
  }
  function renderMetrics(data){const host=qs('#metricCards');host.innerHTML='';[['Usuarios',data.usuarios],['Articulos',data.articulos],['Publicados',data.publicados],['En revision',data.revision],['Comentarios pendientes',data.comentariosPendientes],['Favoritos',data.favoritos],['Vistas',data.vistas]].forEach(([label,value])=>{const c=document.createElement('div');c.className='metric-card';const s=document.createElement('span');s.textContent=label;const strong=document.createElement('strong');strong.textContent=Number(value||0).toLocaleString('es-PE');c.append(s,strong);host.appendChild(c);});}
  function renderTop(items){const host=qs('#topArticles');host.innerHTML='';items.forEach(item=>{const row=document.createElement('div');row.className='compact-row';const title=document.createElement('strong');title.textContent=item.titulo;const views=document.createElement('span');views.textContent=Number(item.vistas).toLocaleString('es-PE')+' vistas';row.append(title,views);host.appendChild(row);});if(!items.length)host.textContent='Sin datos aun.';}
  function renderChart(items){const canvas=qs('#viewsChart');if(!canvas||typeof Chart==='undefined')return;if(viewsChart)viewsChart.destroy();viewsChart=new Chart(canvas,{type:'line',data:{labels:items.map(i=>i.fecha),datasets:[{label:'Vistas',data:items.map(i=>i.vistas),tension:.25}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});}
  function renderAudit(items){const body=qs('#auditTable');if(!body)return;body.innerHTML='';items.forEach(item=>{const tr=document.createElement('tr');tr.append(cell(ui.formatDate(item.createdAt)),cell(item.usuario||'Sistema'),cell(item.accion),cell(item.entidad+(item.entidadId?' #'+item.entidadId:'')),cell(item.ip||''));body.appendChild(tr);});}
  async function loadArticles(page){articlePage=page||1;const p=new URLSearchParams({editorial:'true',page:String(articlePage),size:'20'});const q=qs('#adminArticleQuery').value.trim(),status=qs('#adminArticleStatus').value;if(q)p.set('q',q);if(status)p.set('status',status);try{const data=await api.get('/api/v1/articles?'+p.toString());renderArticlesTable(data.items);ui.pagination(qs('#adminArticlesPagination'),data.page,data.totalPages,loadArticles);}catch(e){qs('#articlesTable').innerHTML='';}}
  function renderArticlesTable(items){const body=qs('#articlesTable');body.innerHTML='';items.forEach(a=>{const tr=document.createElement('tr');tr.append(cell(a.titulo),cell(a.autorNombre));const state=document.createElement('td');state.appendChild(badge(a.estado));tr.append(state,cell(a.vistas),cell(ui.formatDate(a.updatedAt)));const actions=document.createElement('td');actions.className='table-actions';actions.append(action('Editar',()=>editArticle(a.id)));const preview=document.createElement('a');preview.textContent='Vista';preview.target='_blank';preview.href=api.context+'/preview.jsp?id='+a.id;actions.appendChild(preview);actions.append(action('Archivar',()=>archiveArticle(a.id)));tr.appendChild(actions);body.appendChild(tr);});if(!items.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=6;td.textContent='No hay articulos para mostrar.';tr.appendChild(td);body.appendChild(tr);}}
  async function editArticle(id){try{const a=await api.get('/api/v1/articles/'+id+'/preview');currentArticleId=id;qs('#editorHeading').textContent='Editar articulo';qs('#articleTitle').value=a.titulo||'';qs('#articleExcerpt').value=a.extracto||'';qs('#articleContent').innerHTML=a.contenido||'';qs('#articleStatus').value=a.estado;qs('#articleScheduled').value=a.programadoAt?toLocalInput(a.programadoAt):'';qs('#articleAuthor').value=String(a.autorId);qs('#articleCategory').value=a.categoriaId==null?'':String(a.categoriaId);qs('#articleFeatured').checked=!!a.destacado;qs('#articleCover').value=a.portadaUrl||'';qs('#seoTitle').value=a.seoTitulo||'';qs('#seoDescription').value=a.seoDescripcion||'';qs('#seoCanonical').value=a.seoCanonical||'';qs('#seoImage').value=a.seoImagen||'';qs('#previewLink').href=api.context+'/preview.jsp?id='+id;qs('#previewLink').classList.remove('d-none');await loadVersions(id);openPanel('editor');}catch(e){alert(e.message);}}
  async function archiveArticle(id){if(!confirm('Archivar este articulo?'))return;try{await api.delete('/api/v1/articles/'+id);loadArticles(articlePage);}catch(e){alert(e.message);}}
  function clearEditor(){currentArticleId=null;qs('#articleEditorForm').reset();qs('#articleContent').innerHTML='';qs('#editorHeading').textContent='Nuevo articulo';qs('#previewLink').classList.add('d-none');qs('#versionHistory').innerHTML='<p class="muted">Guarda el articulo para crear el historial.</p>';if(currentUser.rol==='AUTOR')qs('#articleAuthor').value=String(currentUser.id);ui.showMessage(qs('#editorMessage'),'');}
  async function saveArticle(event){event.preventDefault();const state=qs('#articleStatus').value,payload={titulo:qs('#articleTitle').value,extracto:qs('#articleExcerpt').value,contenido:qs('#articleContent').innerHTML,estado:state,autorId:Number(qs('#articleAuthor').value||currentUser.id),categoriaId:qs('#articleCategory').value?Number(qs('#articleCategory').value):null,destacado:qs('#articleFeatured').checked,portadaUrl:qs('#articleCover').value||null,programadoAt:qs('#articleScheduled').value?new Date(qs('#articleScheduled').value).toISOString():null,seoTitulo:qs('#seoTitle').value||null,seoDescripcion:qs('#seoDescription').value||null,seoCanonical:qs('#seoCanonical').value||null,seoImagen:qs('#seoImage').value||null};try{const saved=currentArticleId?await api.put('/api/v1/articles/'+currentArticleId,payload):await api.post('/api/v1/articles',payload);currentArticleId=saved.id;qs('#editorHeading').textContent='Editar articulo';qs('#previewLink').href=api.context+'/preview.jsp?id='+saved.id;qs('#previewLink').classList.remove('d-none');ui.showMessage(qs('#editorMessage'),'Articulo guardado','success');await loadVersions(saved.id);}catch(e){ui.showMessage(qs('#editorMessage'),e.message,'error');}}
  async function loadVersions(id){const host=qs('#versionHistory');host.innerHTML='';try{const items=await api.get('/api/v1/articles/'+id+'/versions');items.forEach(v=>{const row=document.createElement('div');row.className='compact-row';const text=document.createElement('strong');text.textContent=v.titulo;const meta=document.createElement('span');meta.textContent=(v.editor||'Sistema')+' | '+ui.formatDate(v.createdAt);const restore=action('Restaurar',()=>restoreVersion(id,v.id));restore.className='text-button';row.append(text,meta,restore);host.appendChild(row);});if(!items.length)host.textContent='Aun no hay versiones anteriores.';}catch(e){host.textContent='No se pudo cargar el historial.';}}
  async function restoreVersion(id,versionId){if(!confirm('Restaurar esta version? El estado editorial y la configuracion actual se conservaran.'))return;try{const a=await api.post('/api/v1/articles/'+id+'/versions/'+versionId+'/restore',{});qs('#articleTitle').value=a.titulo||'';qs('#articleExcerpt').value=a.extracto||'';qs('#articleContent').innerHTML=a.contenido||'';ui.showMessage(qs('#editorMessage'),'Version restaurada','success');await loadVersions(id);}catch(e){ui.showMessage(qs('#editorMessage'),e.message,'error');}}
  function toLocalInput(value){const d=new Date(value),pad=n=>String(n).padStart(2,'0');return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'T'+pad(d.getHours())+':'+pad(d.getMinutes());}
  async function loadCategories(){try{const items=await api.get('/api/v1/categories?all=true');categories=items;const body=qs('#categoriesTable');body.innerHTML='';items.forEach(c=>{const tr=document.createElement('tr');tr.append(cell(c.nombre),cell(c.slug));const state=document.createElement('td');state.appendChild(badge(c.activa?'PUBLICADO':'ARCHIVADO'));tr.append(state,cell(c.orden));const a=document.createElement('td');a.className='table-actions';a.append(action('Editar',()=>fillCategory(c)),action('Desactivar',()=>deleteCategory(c.id)));tr.appendChild(a);body.appendChild(tr);});}catch(e){}}
  function fillCategory(c){qs('#categoryId').value=c.id;qs('#categoryName').value=c.nombre||'';qs('#categorySlug').value=c.slug||'';qs('#categoryDescription').value=c.descripcion||'';qs('#categoryCover').value=c.portadaUrl||'';qs('#categoryOrder').value=c.orden||0;qs('#categoryActive').checked=!!c.activa;qs('#categoryFormTitle').textContent='Editar categoria';}
  async function saveCategory(e){e.preventDefault();const id=qs('#categoryId').value,payload={nombre:qs('#categoryName').value,slug:qs('#categorySlug').value,descripcion:qs('#categoryDescription').value,portadaUrl:qs('#categoryCover').value||null,orden:Number(qs('#categoryOrder').value||0),activa:qs('#categoryActive').checked};try{if(id)await api.put('/api/v1/categories/'+id,payload);else await api.post('/api/v1/categories',payload);ui.showMessage(qs('#categoryMessage'),'Categoria guardada','success');resetCategory();await Promise.all([loadCategories(),loadOptions()]);}catch(err){ui.showMessage(qs('#categoryMessage'),err.message,'error');}}
  function resetCategory(){qs('#categoryForm').reset();qs('#categoryId').value='';qs('#categoryActive').checked=true;qs('#categoryFormTitle').textContent='Categoria';}
  async function deleteCategory(id){if(!confirm('Desactivar categoria?'))return;try{await api.delete('/api/v1/categories/'+id);loadCategories();}catch(e){alert(e.message);}}
  async function loadUsers(){if(currentUser.rol!=='ADMIN')return;const p=new URLSearchParams({page:'1',size:'100'}),q=qs('#userQuery').value.trim(),role=qs('#userRole').value;if(q)p.set('q',q);if(role)p.set('role',role);try{const data=await api.get('/api/v1/users?'+p.toString());const body=qs('#usersTable');body.innerHTML='';data.items.forEach(u=>{const tr=document.createElement('tr');const name=document.createElement('input');name.value=u.nombre;const ntd=document.createElement('td');ntd.appendChild(name);tr.append(ntd,cell(u.email));const roleSelect=document.createElement('select');['ADMIN','EDITOR','AUTOR','LECTOR'].forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;o.selected=r===u.rol;roleSelect.appendChild(o);});const rtd=document.createElement('td');rtd.appendChild(roleSelect);const active=document.createElement('input');active.type='checkbox';active.checked=u.activo;const atd=document.createElement('td');atd.append(active,document.createTextNode(' Activo'));const actions=document.createElement('td');actions.className='table-actions';actions.append(action('Guardar',async()=>{try{await api.put('/api/v1/users/'+u.id,{name:name.value,role:roleSelect.value,active:active.checked});loadUsers();}catch(e){alert(e.message);}}));if(u.id!==currentUser.id)actions.append(action('Desactivar',async()=>{if(confirm('Desactivar usuario?')){await api.delete('/api/v1/users/'+u.id);loadUsers();}}));tr.append(rtd,atd,actions);body.appendChild(tr);});}catch(e){}}
  async function loadComments(){try{const status=qs('#commentStatusFilter').value,p='/api/v1/comments?admin=true&size=100'+(status?'&status='+encodeURIComponent(status):'');const data=await api.get(p),host=qs('#adminComments');host.innerHTML='';data.items.forEach(c=>{const item=document.createElement('article');item.className='moderation-item';const meta=document.createElement('div');meta.className='moderation-meta';const who=document.createElement('strong');who.textContent=c.nombre;const state=badge(c.estado);meta.append(who,state);const text=document.createElement('p');text.textContent=c.contenido;const actions=document.createElement('div');actions.className='moderation-actions';['APROBADO','OCULTO','RECHAZADO'].forEach(s=>actions.append(action(s,async()=>{await api.put('/api/v1/comments/'+c.id,{status:s});loadComments();})));actions.append(action('Eliminar',async()=>{if(confirm('Eliminar comentario?')){await api.delete('/api/v1/comments/'+c.id);loadComments();}}));item.append(meta,text,actions);host.appendChild(item);});if(!data.items.length)host.textContent='No hay comentarios para moderar.';}catch(e){}}
  async function loadMedia(){try{const items=await api.get('/api/v1/media'),host=qs('#mediaGrid');host.innerHTML='';items.forEach(m=>{const item=document.createElement('article');item.className='media-item';const img=document.createElement('img');img.src=ui.safeImage(m.url);img.alt=m.nombreArchivo;const info=document.createElement('div');info.className='media-info';const name=document.createElement('strong');name.textContent=m.nombreArchivo;const acts=document.createElement('div');acts.append(action('Usar',()=>{qs('#articleCover').value=m.url;openPanel('editor');}),action('Copiar',()=>navigator.clipboard.writeText(new URL(m.url,location.origin).href)));if(currentUser.rol!=='AUTOR')acts.append(action('Eliminar',async()=>{if(confirm('Eliminar archivo?')){await api.delete('/api/v1/media/'+m.id);loadMedia();}}));info.append(name,acts);item.append(img,info);host.appendChild(item);});if(!items.length)host.textContent='La biblioteca esta vacia.';}catch(e){}}
  async function uploadMedia(e){e.preventDefault();const file=qs('#mediaFile').files[0],m=qs('#mediaMessage');if(!file)return;const form=new FormData();form.append('file',file);try{await api.request('/api/v1/media',{method:'POST',body:form});e.currentTarget.reset();ui.showMessage(m,'Imagen subida','success');loadMedia();}catch(err){ui.showMessage(m,err.message,'error');}}
  async function loadHomeSections(){try{renderSections(await api.get('/api/v1/dashboard/sections'));}catch(e){}}
  function renderSections(items){const host=qs('#homeSections');if(!host)return;host.innerHTML='';items.forEach(s=>{const row=document.createElement('div');row.className='setting-item';const title=document.createElement('input');title.value=s.titulo;const titleLabel=document.createElement('label');titleLabel.textContent='Titulo';titleLabel.appendChild(title);const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=s.habilitada;const enabledLabel=document.createElement('label');enabledLabel.textContent='Visible';enabledLabel.appendChild(enabled);const position=document.createElement('input');position.type='number';position.min='0';position.value=s.posicion;const posLabel=document.createElement('label');posLabel.textContent='Posicion';posLabel.appendChild(position);const limit=document.createElement('input');limit.type='number';limit.min='1';limit.max='24';limit.value=s.limiteItems;const limitLabel=document.createElement('label');limitLabel.textContent='Limite';limitLabel.appendChild(limit);const save=action('Guardar',async()=>{try{await api.put('/api/v1/dashboard/sections/'+s.id,{title:title.value,enabled:enabled.checked,position:Number(position.value),limitItems:Number(limit.value)});loadHomeSections();}catch(e){alert(e.message);}});save.className='editorial-button small';row.append(titleLabel,enabledLabel,posLabel,limitLabel,save);host.appendChild(row);});}
  function editorToolbar(){qsa('.editor-toolbar button').forEach(button=>button.addEventListener('click',()=>{let value=button.dataset.value||null;if(button.dataset.command==='createLink'){value=prompt('URL del enlace');if(!value||!/^https?:\/\//i.test(value))return;}document.execCommand(button.dataset.command,false,value);qs('#articleContent').focus();}));}
  qsa('.admin-nav').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));qsa('[data-open-editor]').forEach(b=>b.addEventListener('click',()=>{clearEditor();openPanel('editor');}));qsa('[data-panel-jump]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panelJump)));
  qs('#openSidebar').addEventListener('click',()=>qs('#adminSidebar').classList.add('open'));qs('#closeSidebar').addEventListener('click',()=>qs('#adminSidebar').classList.remove('open'));
  qs('#adminLogout').addEventListener('click',async()=>{try{await api.post('/api/v1/auth/logout',{});}finally{location.href=api.context+'/index.jsp';}});qs('[data-refresh="dashboard"]').addEventListener('click',loadDashboard);
  qs('#adminArticleFilters').addEventListener('submit',e=>{e.preventDefault();loadArticles(1);});qs('#articleEditorForm').addEventListener('submit',saveArticle);qs('#clearEditor').addEventListener('click',clearEditor);qs('#categoryForm').addEventListener('submit',saveCategory);qs('#newCategory').addEventListener('click',resetCategory);qs('#userFilters').addEventListener('submit',e=>{e.preventDefault();loadUsers();});qs('#refreshComments').addEventListener('click',loadComments);qs('#commentStatusFilter').addEventListener('change',loadComments);qs('#mediaUploadForm').addEventListener('submit',uploadMedia);editorToolbar();initialize();
})();
