// Interacciones de la pagina de articulo.
(function(){
  const api=window.JeanPipiApi,ui=window.JeanPipiUI,id=Number(document.querySelector('meta[name="article-id"]').content);let sessionUser=null;
  async function session(){try{const data=await api.get('/api/v1/auth/session');sessionUser=data.user;if(sessionUser)document.getElementById('guestCommentFields').classList.add('d-none');return data.user;}catch(e){return null;}}
  async function registerView(){const key='jp-view-'+id;if(sessionStorage.getItem(key))return;try{await api.post('/api/v1/articles/'+id+'/view',{});sessionStorage.setItem(key,'1');}catch(e){}}
  async function loadRelated(){try{ui.renderArticles(document.getElementById('relatedGrid'),await api.get('/api/v1/articles/'+id+'/related?limit=4'));}catch(e){}}
  async function loadComments(){const list=document.getElementById('commentsList');try{const items=await api.get('/api/v1/comments?articleId='+id);list.innerHTML='';if(!items.length){const p=document.createElement('p');p.className='muted';p.textContent='Aun no hay comentarios aprobados.';list.appendChild(p);return;}items.forEach(item=>{const box=document.createElement('article');box.className='comment-item';const name=document.createElement('strong');name.textContent=item.nombre;const time=document.createElement('time');time.textContent=ui.formatDate(item.createdAt);const text=document.createElement('p');text.textContent=item.contenido;box.append(name,time,text);list.appendChild(box);});}catch(e){list.textContent='No se pudieron cargar los comentarios.';}}
  async function favoriteState(){const button=document.getElementById('favoriteButton');if(!sessionUser){button.innerHTML='<i class="bi bi-bookmark"></i> Guardar';return;}try{const data=await api.get('/api/v1/favorites/'+id);renderFavorite(button,data.favorite);}catch(e){}}
  function renderFavorite(button,value){button.dataset.favorite=String(value);button.innerHTML=value?'<i class="bi bi-bookmark-fill"></i> Guardado':'<i class="bi bi-bookmark"></i> Guardar';}
  document.getElementById('favoriteButton').addEventListener('click',async e=>{if(!sessionUser){location.href=api.context+'/login.jsp?next='+encodeURIComponent(location.pathname.substring(api.context.length+1));return;}try{const data=await api.post('/api/v1/favorites/'+id,{});renderFavorite(e.currentTarget,data.favorite);}catch(err){}});
  document.getElementById('commentForm').addEventListener('submit',async e=>{e.preventDefault();const m=document.getElementById('commentMessage');try{await api.post('/api/v1/comments',{articuloId:id,nombre:document.getElementById('commentName').value,email:document.getElementById('commentEmail').value,contenido:document.getElementById('commentContent').value});e.currentTarget.reset();ui.showMessage(m,'Comentario enviado. Queda pendiente de moderacion.','success');}catch(err){ui.showMessage(m,err.message,'error');}});
  document.querySelector('[data-share="native"]').addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);alert('Enlace copiado');}}catch(e){}});
  (async()=>{await session();favoriteState();registerView();loadRelated();loadComments();})();
})();
