// Formularios de autenticacion.
(function(){
  const api=window.JeanPipiApi,ui=window.JeanPipiUI,message=document.getElementById('authMessage');
  function redirectAfterAuth(){const p=new URLSearchParams(location.search),next=p.get('next');if(next&&/^[A-Za-z0-9._\/-]+$/.test(next))location.href=api.context+'/'+next.replace(/^\//,'');else location.href=api.context+'/index.jsp';}
  const login=document.getElementById('loginForm');if(login)login.addEventListener('submit',async e=>{e.preventDefault();ui.showMessage(message,'Ingresando...');try{await api.post('/api/v1/auth/login',{email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value});ui.showMessage(message,'Sesion iniciada','success');redirectAfterAuth();}catch(err){ui.showMessage(message,err.message,'error');}});
  const register=document.getElementById('registerForm');if(register)register.addEventListener('submit',async e=>{e.preventDefault();ui.showMessage(message,'Creando cuenta...');try{await api.post('/api/v1/auth/register',{name:document.getElementById('registerName').value,email:document.getElementById('registerEmail').value,password:document.getElementById('registerPassword').value});ui.showMessage(message,'Cuenta creada','success');redirectAfterAuth();}catch(err){ui.showMessage(message,err.message,'error');}});
  const forgot=document.getElementById('forgotForm');if(forgot)forgot.addEventListener('submit',async e=>{e.preventDefault();ui.showMessage(message,'Procesando...');try{const data=await api.post('/api/v1/auth/forgot-password',{email:document.getElementById('forgotEmail').value});ui.showMessage(message,data.message,'success');}catch(err){ui.showMessage(message,err.message,'error');}});
  const reset=document.getElementById('resetForm');if(reset)reset.addEventListener('submit',async e=>{e.preventDefault();const token=new URLSearchParams(location.search).get('token');if(!token){ui.showMessage(message,'El enlace no contiene un token valido','error');return;}try{const data=await api.post('/api/v1/auth/reset-password',{token,password:document.getElementById('resetPassword').value});ui.showMessage(message,data.message,'success');setTimeout(()=>location.href=api.context+'/login.jsp',900);}catch(err){ui.showMessage(message,err.message,'error');}});
})();
